<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="zhangyj01" name="CatcherDemo" tests="4" failures="3" timestamp="15 Sep 2014 10:03:21 GMT" time="65.971" errors="0">
  <testcase name="alertBtn" time="3.473" classname="com.test.catcher.Demo1">
    <failure type="java.lang.AssertionError" message="expected [aa] but found [I am an alert box!!]">
      <![CDATA[java.lang.AssertionError: expected [aa] but found [I am an alert box!!]
	at com.test.catcher.Demo1.alertBtn(Demo1.java:66)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- alertBtn -->
  <testcase name="alertBtn" time="3.501" classname="com.test.catcher.Demo1">
    <failure type="java.lang.AssertionError" message="expected [aa] but found [I am an alert box!!]">
      <![CDATA[java.lang.AssertionError: expected [aa] but found [I am an alert box!!]
	at com.test.catcher.Demo1.alertBtn(Demo1.java:66)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- alertBtn -->
  <testcase name="alertBtn" time="3.43" classname="com.test.catcher.Demo1">
    <failure type="java.lang.AssertionError" message="expected [aa] but found [I am an alert box!!]">
      <![CDATA[java.lang.AssertionError: expected [aa] but found [I am an alert box!!]
	at com.test.catcher.Demo1.alertBtn(Demo1.java:66)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- alertBtn -->
  <testcase name="multiFrame" time="9.746" classname="com.test.catcher.Demo1"/>
</testsuite> <!-- CatcherDemo -->
